### ISSUE TITLE
rosdoc_lite: fix documentation on wiki.ros.org

### ISSUE THREAD

**Issue by jack-oquin** [ros-infrastructure/rosdoc_lite#37]

**Comment by davetcoleman** [comment]
I think this question goes here... it appears there is no longer correct steps on the main wiki page http://wiki.ros.org/rosdoc_lite :

```
In order to enable the rosdoc configuration file, you must place the following tag in the <export>...</export> section of the package.xml (or manifest.xml in rosbuild-based packages, which is getting less standard after ROS Hydro) file:

<export>
  <rosdoc config="rosdoc.yaml" />
</export>
rosdoc.yaml should be the path to the configuration file you wish to use.
```

Because https://github.com/ros-planning/moveit_ros/tree/kinetic-devel/visualization does not have that tag in its package.xml but everything still builds fine and is live on the website. I'll remove it if someone +1's this

**Comment by jack-oquin** [comment]
+1, but note that the export is probably still necessary if you choose to name the file something other than ``rosdoc.yaml``.

**Comment by davetcoleman** [comment]
Done.

```
In order to enable the rosdoc configuration file, simply have a rosdoc.yaml file in the root of your package. If you wish to name it something else, you must place the following tag in the <export>...</export> section of the package.xml, but this behavior is old:
```

I also removed "new in Fuerte" ;-)

**Comment by jack-oquin** [comment]
Thanks, Dave!
